#!/bin/sh

# sqlite3 ~/.config/chromium/Default/Cookies "SELECT * FROM cookies WHERE host_key='0.0.0.0'" | less
while getopts "c:l:" opt; do
	
	case $opt in 
		c)
			case "$OPTARG" in 
				all)
					sqlite3 databases/users.db 'UPDATE users SET chatrooms = ""'
					sqlite3 databases/users.db 'DELETE FROM users WHERE name != "#ONE" AND name != "#TWO"'
					sqlite3 ~/.config/chromium/Default/Cookies 'DELETE FROM cookies WHERE host_key="0.0.0.0"' 

					if [ -f "databases/chatrooms.db" ]; then
						command -v doas > /dev/null &&
						doas rm -r databases/chatrooms.db || 
						sudo rm -r databases/chatrooms.db 
					fi

					echo "cleared all data"
				;;

			esac
		;;

		l)
			case "$OPTARG" in 
				admins)
					sqlite3 databases/users.db "SELECT name FROM users WHERE name LIKE '#%'"
				;;

				all)
					echo "USERS"
					sqlite3 databases/users.db "SELECT name FROM users"
					echo -e "-----------\n"
					echo -e "COOKIES\n"

					echo -e "  chromium\n"
					sqlite3 ~/.config/chromium/Default/Cookies "SELECT * FROM cookies WHERE host_key='0.0.0.0'"  | sed 's/^/    /'
					echo -e "\n"

					echo -e "  brave\n"
					sqlite3 ~/.config/BraveSoftware/Brave-Browser/Default/Cookies "SELECT * FROM cookies WHERE host_key='0.0.0.0'" | sed 's/^/    /'

					echo "-----------"

				;;
			esac
		;;

	esac

done
